url: https://mahe.orthosam.com
title: Orthosam
description: for manipal
show_downloads: false
show_posts: false
theme: jekyll-theme-slate
timezone: Asia/Calcutta
exclude: [exclude]
keep_files: [keep]
include: [include]
permalink: pretty
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
