var drugs = {
"PARACETAMOL": null,
"PANTOPRAZOLE": null,
"TRAMADOL": null,
"LEVOTHYROXINE": null,
"OMEPRAZOLE": null,
"AMLODIPINE": null,
"ATORVASTATIN": null,
"METFORMIN": null,
"METOPROLOL": null,
"GABAPENTIN": null,
"ALPRAZOLAM": null,
"MONTELUKAST": null,
"BUPROPION": null,
"CLONAZEPAM": null,
"CLOPIDOGREL": null,
"PREDNISONE": null,
"ASPIRIN": null,
"TAPROFEN": null,
"LISINOPRIL": null,
"VENLAFAXINE": null,
"WARFARIN": null,
"CYCLOBENZAPRINE": null,
"TAMSIN": null,
"ZOLPIDEM": null,
"DULOXETINE": null,
"RANITIDINE": null
}
